# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FAPCzF4qlSbMdVxGzfRduDRqfH2JTGBK
"""

from sklearn.preprocessing import normalize
import numpy as np

# create a sample dataset
X = np.array([[1, 2], [3, 4]])

# normalize the dataset
X_normalized = normalize(X)

print("Original dataset:\n", X)
print("Normalized dataset:\n", X_normalized)