# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17aR2PohW0nRqkWgFJNrrmS0qeFcnnmBd
"""

import numpy as np
import seaborn as sns
import pandas as pd

from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression

df=sns.load_dataset('iris')

from sklearn.model_selection import train_test_split

X = df.iloc[:,:-1]
y = df.iloc[:,-1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

solvers = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

# Dictionary to store results
results = {}

for solver in solvers:
    # Create a logistic regression model with the current solver
    model = LogisticRegression(solver=solver)

    # Train the model
    model.fit(X_train, y_train)

    # Make predictions on the test set
    y_pred = model.predict(X_test)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)

    # Store the result in the dictionary
    results[solver] = accuracy

# Print results
for solver, accuracy in results.items():
    print(f"Solver: {solver}, Accuracy: {accuracy}")