# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U2KzwoYNcVs1b9M9ZdWrh2uaWrkp7KsZ
"""

import pytest
import requests

def test_post_predict():
    url = "http://localhost:5000/predict"
    # Define the test data
    test_data = [
        {"input": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "output": 0},
        {"input": [0, 0, 0, 0, 0, 0, 0, 0, 0, 1], "output": 1},
        {"input": [0, 0, 0, 0, 0, 0, 0, 0, 1, 0], "output": 2},
        {"input": [0, 0, 0, 0, 0, 0, 0, 0, 1, 1], "output": 3},
        {"input": [0, 0, 0, 0, 0, 0, 0, 1, 0, 0], "output": 4},
        {"input": [0, 0, 0, 0, 0, 0, 0, 1, 0, 1], "output": 5},
        {"input": [0, 0, 0, 0, 0, 0, 0, 1, 1, 0], "output": 6},
        {"input": [0, 0, 0, 0, 0, 0, 0, 1, 1, 1], "output": 7},
        {"input": [0, 0, 0, 0, 0, 0, 1, 0, 0, 0], "output": 8},
        {"input": [0, 0, 0, 0, 0, 0, 1, 0, 0, 1], "output": 9},
        {"input": [0, 0, 0, 0, 0, 0, 1, 0, 1, 0], "output": 0},
    ]

    # Send a POST request for each test case and check the response
    for data in test_data:
        response = requests.post(url, json={"input": data["input"]})
        assert response.status_code == 200
        assert response.json()["output"] == data["output"]