name: Logistic Regression Solver Performance

on:
  push:
    branches:
      - main

jobs:
  logistic_regression:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Add your dependencies file if needed

    - name: Run logistic regression script
      run: python q2.py
